# MongoDB configuration
spring.data.mongodb.uri=${MONGO_URI}

# Cloudinary configuratio
cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_SECRET_KEY}

admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}

# File upload configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#jwt information
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

server.port=${PORT:8080}